/*
 * manualWords.js — PDF listelerinde olmayan, elle eklenen kelimeler.
 *
 * Her seviye PDF'inden gelen benzersiz kelime sayısı 900'ün altındaysa,
 * eksik kalan kısım buradaki seviyeye-uygun, doğrulanmış kelimelerle tamamlanır.
 *
 * KURALLAR (buildWords.js bunları kod ile zorlar):
 *  - Buraya eklenen hiçbir kelime, herhangi bir PDF seviyesinde bulunmamalıdır.
 *  - Aynı kelime birden fazla seviyede / birden fazla kez olmamalıdır.
 *  - Kelime, eklendiği seviyenin zorluğuna uygun olmalıdır (A1 = en temel).
 *
 * Format: { word, translation, meanings: [...] }  (sentence/synonyms/opposites script'te eklenir)
 */

module.exports = {
  A1: [
    { word: 'tiger', translation: 'kaplan', meanings: ['kaplan'] },
    { word: 'rabbit', translation: 'tavşan', meanings: ['tavşan'] },
    { word: 'duck', translation: 'ördek', meanings: ['ördek'] },
    { word: 'grape', translation: 'üzüm', meanings: ['üzüm'] },
    { word: 'cherry', translation: 'kiraz', meanings: ['kiraz', 'vişne'] },
    { word: 'cookie', translation: 'kurabiye', meanings: ['kurabiye', 'bisküvi'] },
    { word: 'honey', translation: 'bal', meanings: ['bal'] },
    { word: 'pillow', translation: 'yastık', meanings: ['yastık'] },
    { word: 'rainbow', translation: 'gökkuşağı', meanings: ['gökkuşağı'] },
    { word: 'peach', translation: 'şeftali', meanings: ['şeftali'] },
    { word: 'goat', translation: 'keçi', meanings: ['keçi'] },
    { word: 'eraser', translation: 'silgi', meanings: ['silgi'] },
    { word: 'ruler', translation: 'cetvel', meanings: ['cetvel'] },
    { word: 'backpack', translation: 'sırt çantası', meanings: ['sırt çantası'] },
    { word: 'pasta', translation: 'makarna', meanings: ['makarna'] },
    { word: 'candy', translation: 'şeker', meanings: ['şeker', 'şekerleme'] },
  ],
  A2: [
    { word: "jealous", translation: "kıskanç", meanings: ["kıskanç"] },
    { word: "gloomy", translation: "karamsar", meanings: ["karamsar","kasvetli"] },
    { word: "giggle", translation: "kıkırdamak", meanings: ["kıkırdamak"] },
    { word: "sneeze", translation: "hapşırmak", meanings: ["hapşırmak"] },
    { word: "yawn", translation: "esnemek", meanings: ["esnemek"] },
    { word: "sniff", translation: "koklamak", meanings: ["koklamak"] },
    { word: "blink", translation: "göz kırpmak", meanings: ["göz kırpmak"] },
    { word: "frown", translation: "kaş çatmak", meanings: ["kaş çatmak"] },
    { word: "peel", translation: "soymak", meanings: ["soymak"] },
    { word: "roast", translation: "kavurmak", meanings: ["kavurmak","fırınlamak"] },
    { word: "mop", translation: "paspaslamak", meanings: ["paspaslamak"] },
    { word: "scrub", translation: "ovalamak", meanings: ["ovalamak"] },
    { word: "rinse", translation: "durulamak", meanings: ["durulamak"] },
    { word: "mattress", translation: "şilte", meanings: ["şilte","yatak"] },
    { word: "wardrobe", translation: "gardırop", meanings: ["gardırop","dolap"] },
    { word: "drawer", translation: "çekmece", meanings: ["çekmece"] },
    { word: "stool", translation: "tabure", meanings: ["tabure"] },
    { word: "fountain", translation: "çeşme", meanings: ["çeşme","fıskiye"] },
    { word: "lantern", translation: "fener", meanings: ["fener"] },
    { word: "bucket", translation: "kova", meanings: ["kova"] },
    { word: "broom", translation: "süpürge", meanings: ["süpürge"] },
    { word: "hammer", translation: "çekiç", meanings: ["çekiç"] },
    { word: "shovel", translation: "kürek", meanings: ["kürek"] },
    { word: "rake", translation: "tırmık", meanings: ["tırmık"] },
    { word: "barn", translation: "ahır", meanings: ["ahır","samanlık"] },
    { word: "squirrel", translation: "sincap", meanings: ["sincap"] },
    { word: "hedgehog", translation: "kirpi", meanings: ["kirpi"] },
    { word: "owl", translation: "baykuş", meanings: ["baykuş"] },
    { word: "eagle", translation: "kartal", meanings: ["kartal"] },
    { word: "sparrow", translation: "serçe", meanings: ["serçe"] },
    { word: "pigeon", translation: "güvercin", meanings: ["güvercin"] },
    { word: "seagull", translation: "martı", meanings: ["martı"] },
    { word: "dolphin", translation: "yunus", meanings: ["yunus"] },
    { word: "whale", translation: "balina", meanings: ["balina"] },
    { word: "shark", translation: "köpekbalığı", meanings: ["köpekbalığı"] },
    { word: "octopus", translation: "ahtapot", meanings: ["ahtapot"] },
    { word: "crab", translation: "yengeç", meanings: ["yengeç"] },
    { word: "lobster", translation: "ıstakoz", meanings: ["ıstakoz"] },
    { word: "jellyfish", translation: "denizanası", meanings: ["denizanası"] },
    { word: "snail", translation: "salyangoz", meanings: ["salyangoz"] },
    { word: "beetle", translation: "böcek", meanings: ["böcek","kınkanatlı"] },
    { word: "caterpillar", translation: "tırtıl", meanings: ["tırtıl"] },
    { word: "grasshopper", translation: "çekirge", meanings: ["çekirge"] },
    { word: "dragonfly", translation: "yusufçuk", meanings: ["yusufçuk"] },
    { word: "moth", translation: "güve", meanings: ["güve","pervane"] },
    { word: "wasp", translation: "eşekarısı", meanings: ["eşekarısı"] },
    { word: "scorpion", translation: "akrep", meanings: ["akrep"] },
    { word: "lizard", translation: "kertenkele", meanings: ["kertenkele"] },
    { word: "turtle", translation: "kaplumbağa", meanings: ["kaplumbağa"] },
    { word: "toad", translation: "kara kurbağası", meanings: ["kara kurbağası"] },
    { word: "pumpkin", translation: "balkabağı", meanings: ["balkabağı"] },
    { word: "cabbage", translation: "lahana", meanings: ["lahana"] },
    { word: "spinach", translation: "ıspanak", meanings: ["ıspanak"] },
    { word: "broccoli", translation: "brokoli", meanings: ["brokoli"] },
    { word: "celery", translation: "kereviz", meanings: ["kereviz"] },
    { word: "radish", translation: "turp", meanings: ["turp"] },
    { word: "turnip", translation: "şalgam", meanings: ["şalgam"] },
    { word: "pea", translation: "bezelye", meanings: ["bezelye"] },
    { word: "lentil", translation: "mercimek", meanings: ["mercimek"] },
    { word: "walnut", translation: "ceviz", meanings: ["ceviz"] },
    { word: "almond", translation: "badem", meanings: ["badem"] },
    { word: "peanut", translation: "yer fıstığı", meanings: ["yer fıstığı"] },
    { word: "hazelnut", translation: "fındık", meanings: ["fındık"] },
    { word: "raisin", translation: "kuru üzüm", meanings: ["kuru üzüm"] },
    { word: "apricot", translation: "kayısı", meanings: ["kayısı"] },
    { word: "plum", translation: "erik", meanings: ["erik"] },
    { word: "fig", translation: "incir", meanings: ["incir"] },
    { word: "coconut", translation: "hindistan cevizi", meanings: ["hindistan cevizi"] },
    { word: "pineapple", translation: "ananas", meanings: ["ananas"] },
    { word: "mango", translation: "mango", meanings: ["mango"] },
    { word: "kiwi", translation: "kivi", meanings: ["kivi"] },
    { word: "strawberry", translation: "çilek", meanings: ["çilek"] },
    { word: "raspberry", translation: "ahududu", meanings: ["ahududu"] },
    { word: "blueberry", translation: "yaban mersini", meanings: ["yaban mersini"] },
    { word: "clap", translation: "alkışlamak", meanings: ["alkışlamak"] },
    { word: "sip", translation: "yudumlamak", meanings: ["yudumlamak"] },
    { word: "chew", translation: "çiğnemek", meanings: ["çiğnemek"] },
    { word: "lick", translation: "yalamak", meanings: ["yalamak"] },
    { word: "cough", translation: "öksürmek", meanings: ["öksürmek"] },
    { word: "snore", translation: "horlamak", meanings: ["horlamak"] },
    { word: "fluffy", translation: "kabarık", meanings: ["kabarık","tüylü"] },
    { word: "slippery", translation: "kaygan", meanings: ["kaygan"] },
    { word: "juicy", translation: "sulu", meanings: ["sulu"] },
    { word: "sour", translation: "ekşi", meanings: ["ekşi"] },
    { word: "salty", translation: "tuzlu", meanings: ["tuzlu"] },
    { word: "tasty", translation: "lezzetli", meanings: ["lezzetli"] },
    { word: "ripe", translation: "olgun", meanings: ["olgun"] },
    { word: "foggy", translation: "sisli", meanings: ["sisli"] },
    { word: "muddy", translation: "çamurlu", meanings: ["çamurlu"] },
    { word: "dusty", translation: "tozlu", meanings: ["tozlu"] },
    { word: "cozy", translation: "rahat", meanings: ["rahat","samimi"] },
    { word: "puppy", translation: "köpek yavrusu", meanings: ["köpek yavrusu"] },
    { word: "kitten", translation: "kedi yavrusu", meanings: ["kedi yavrusu"] },
    { word: "kneel", translation: "diz çökmek", meanings: ["diz çökmek"] },
    { word: "pat", translation: "hafifçe vurmak", meanings: ["hafifçe vurmak","okşamak"] },
    { word: "tickle", translation: "gıdıklamak", meanings: ["gıdıklamak"] },
    { word: "pinch", translation: "çimdiklemek", meanings: ["çimdiklemek"] },
    { word: "splash", translation: "su sıçratmak", meanings: ["su sıçratmak"] },
    { word: "gulp", translation: "yutkunmak", meanings: ["yutkunmak","büyük yudum almak"] },
    { word: "hiccup", translation: "hıçkırık", meanings: ["hıçkırık"] },
    { word: "greasy", translation: "yağlı", meanings: ["yağlı"] },
    { word: "bumpy", translation: "engebeli", meanings: ["engebeli","tümsekli"] },
    { word: "crispy", translation: "çıtır", meanings: ["çıtır","gevrek"] },
    { word: "rotten", translation: "çürük", meanings: ["çürük"] },
    { word: "melted", translation: "erimiş", meanings: ["erimiş"] },
    { word: "frosty", translation: "ayazlı", meanings: ["ayazlı","buz tutmuş"] },
    { word: "wobbly", translation: "sallanan", meanings: ["sallanan","dengesiz"] },
    { word: "calf", translation: "buzağı", meanings: ["buzağı","dana"] },
    { word: "chick", translation: "civciv", meanings: ["civciv"] },
    { word: "duckling", translation: "ördek yavrusu", meanings: ["ördek yavrusu"] },
    { word: "claw", translation: "pençe", meanings: ["pençe"] },
    { word: "beak", translation: "gaga", meanings: ["gaga"] },
    { word: "paw", translation: "hayvan pençesi", meanings: ["hayvan pençesi","pati"] },
  ],
  B1: [
    { word: "sincerity", translation: "içtenlik", meanings: ["içtenlik","samimiyet"] },
    { word: "generosity", translation: "cömertlik", meanings: ["cömertlik"] },
    { word: "jealousy", translation: "kıskançlık", meanings: ["kıskançlık"] },
    { word: "empathy", translation: "empati", meanings: ["empati","duygudaşlık"] },
    { word: "endurance", translation: "dayanıklılık", meanings: ["dayanıklılık","tahammül"] },
    { word: "persistence", translation: "ısrar", meanings: ["ısrar","azim"] },
    { word: "willpower", translation: "irade gücü", meanings: ["irade gücü"] },
    { word: "workflow", translation: "iş akışı", meanings: ["iş akışı"] },
    { word: "milestone", translation: "kilometre taşı", meanings: ["kilometre taşı","dönüm noktası"] },
    { word: "proficiency", translation: "yeterlilik", meanings: ["yeterlilik","ustalık"] },
    { word: "credential", translation: "yeterlilik belgesi", meanings: ["yeterlilik belgesi","referans"] },
    { word: "internship", translation: "staj", meanings: ["staj"] },
    { word: "apprenticeship", translation: "çıraklık", meanings: ["çıraklık"] },
    { word: "syllabus", translation: "ders programı", meanings: ["ders programı","müfredat"] },
    { word: "dissertation", translation: "tez", meanings: ["tez","bilimsel inceleme"] },
    { word: "tutorial", translation: "öğretici", meanings: ["öğretici","ders kılavuzu"] },
    { word: "colloquium", translation: "bilimsel toplantı", meanings: ["bilimsel toplantı","seminer"] },
    { word: "enrollment", translation: "kayıt", meanings: ["kayıt","kaydolma"] },
    { word: "certification", translation: "belgelendirme", meanings: ["belgelendirme","sertifikalandırma"] },
    { word: "condense", translation: "yoğunlaştırmak", meanings: ["yoğunlaştırmak","özetlemek"] },
    { word: "conform", translation: "uymak", meanings: ["uymak","uyum sağlamak"] },
    { word: "dispatch", translation: "göndermek", meanings: ["göndermek","sevk etmek"] },
    { word: "inquire", translation: "sormak", meanings: ["sormak","soruşturmak"] },
    { word: "prioritize", translation: "öncelik vermek", meanings: ["öncelik vermek"] },
    { word: "reconcile", translation: "uzlaştırmak", meanings: ["uzlaştırmak","bağdaştırmak"] },
    { word: "scrutinize", translation: "inceden inceye incelemek", meanings: ["inceden inceye incelemek","irdelemek"] },
    { word: "abundant", translation: "bol", meanings: ["bol","bereketli"] },
    { word: "ambiguous", translation: "belirsiz", meanings: ["belirsiz","muğlak"] },
    { word: "coherent", translation: "tutarlı", meanings: ["tutarlı","anlaşılır"] },
    { word: "feasible", translation: "yapılabilir", meanings: ["yapılabilir","uygulanabilir"] },
    { word: "gradual", translation: "kademeli", meanings: ["kademeli","yavaş yavaş olan"] },
    { word: "intricate", translation: "karmaşık", meanings: ["karmaşık","girift"] },
    { word: "optimal", translation: "en uygun", meanings: ["en uygun","en iyi"] },
    { word: "plausible", translation: "akla yatkın", meanings: ["akla yatkın","makul"] },
    { word: "rigorous", translation: "titiz", meanings: ["titiz","sıkı"] },
    { word: "superficial", translation: "yüzeysel", meanings: ["yüzeysel","sığ"] },
    { word: "versatile", translation: "çok yönlü", meanings: ["çok yönlü","becerikli"] },
    { word: "vigorous", translation: "güçlü", meanings: ["güçlü","dinç"] },
    { word: "anticipation", translation: "bekleyiş", meanings: ["bekleyiş","öngörü"] },
    { word: "clarification", translation: "açıklama", meanings: ["açıklama","aydınlatma"] },
    { word: "compilation", translation: "derleme", meanings: ["derleme"] },
    { word: "comprehension", translation: "kavrama", meanings: ["kavrama","anlama"] },
    { word: "condensation", translation: "yoğunlaşma", meanings: ["yoğunlaşma","buğulanma"] },
    { word: "contemplation", translation: "derin düşünme", meanings: ["derin düşünme","tefekkür"] },
    { word: "cultivation", translation: "yetiştirme", meanings: ["yetiştirme","ekip biçme"] },
    { word: "derivation", translation: "türetme", meanings: ["türetme","köken"] },
    { word: "designation", translation: "atama", meanings: ["atama","adlandırma"] },
    { word: "differentiation", translation: "ayrım", meanings: ["ayrım","farklılaştırma"] },
    { word: "elaboration", translation: "ayrıntılandırma", meanings: ["ayrıntılandırma"] },
    { word: "elimination", translation: "eleme", meanings: ["eleme","ortadan kaldırma"] },
    { word: "enhancement", translation: "iyileştirme", meanings: ["iyileştirme","artırma"] },
    { word: "exaggeration", translation: "abartma", meanings: ["abartma"] },
    { word: "facilitation", translation: "kolaylaştırma", meanings: ["kolaylaştırma"] },
    { word: "formulation", translation: "formülleştirme", meanings: ["formülleştirme","ifade etme"] },
    { word: "imposition", translation: "dayatma", meanings: ["dayatma","yükleme"] },
    { word: "incorporation", translation: "birleştirme", meanings: ["birleştirme","dahil etme"] },
    { word: "inhibition", translation: "engelleme", meanings: ["engelleme","ket vurma"] },
    { word: "initiation", translation: "başlatma", meanings: ["başlatma"] },
    { word: "minimization", translation: "en aza indirme", meanings: ["en aza indirme"] },
    { word: "prohibition", translation: "yasaklama", meanings: ["yasaklama","yasak"] },
    { word: "reinforcement", translation: "pekiştirme", meanings: ["pekiştirme","takviye"] },
    { word: "retention", translation: "akılda tutma", meanings: ["akılda tutma","elde tutma"] },
    { word: "retrieval", translation: "geri alma", meanings: ["geri alma","erişim"] },
    { word: "utilization", translation: "kullanım", meanings: ["kullanım","yararlanma"] },
    { word: "verification", translation: "doğrulama", meanings: ["doğrulama"] },
    { word: "adaptability", translation: "uyum yeteneği", meanings: ["uyum yeteneği"] },
    { word: "affordability", translation: "satın alınabilirlik", meanings: ["satın alınabilirlik","uygun fiyatlılık"] },
    { word: "applicability", translation: "uygulanabilirlik", meanings: ["uygulanabilirlik"] },
    { word: "compatibility", translation: "uyumluluk", meanings: ["uyumluluk"] },
    { word: "durability", translation: "dayanıklılık", meanings: ["dayanıklılık","sağlamlık"] },
    { word: "feasibility", translation: "yapılabilirlik", meanings: ["yapılabilirlik","olabilirlik"] },
    { word: "suitability", translation: "uygunluk", meanings: ["uygunluk"] },
    { word: "sustainability", translation: "sürdürülebilirlik", meanings: ["sürdürülebilirlik"] },
    { word: "accessibility", translation: "erişilebilirlik", meanings: ["erişilebilirlik"] },
    { word: "adequacy", translation: "yeterlilik", meanings: ["yeterlilik"] },
    { word: "continuity", translation: "süreklilik", meanings: ["süreklilik"] },
    { word: "maturity", translation: "olgunluk", meanings: ["olgunluk"] },
    { word: "scarcity", translation: "kıtlık", meanings: ["kıtlık","azlık"] },
    { word: "severity", translation: "şiddet", meanings: ["şiddet","ciddiyet"] },
    { word: "uniformity", translation: "tekdüzelik", meanings: ["tekdüzelik","yeknesaklık"] },
    { word: "boldness", translation: "cesaret", meanings: ["cesaret","atılganlık"] },
    { word: "brightness", translation: "parlaklık", meanings: ["parlaklık"] },
    { word: "cleverness", translation: "zekilik", meanings: ["zekilik","kurnazlık"] },
    { word: "closeness", translation: "yakınlık", meanings: ["yakınlık"] },
    { word: "eagerness", translation: "isteklilik", meanings: ["isteklilik","heves"] },
    { word: "fondness", translation: "düşkünlük", meanings: ["düşkünlük","sevgi"] },
    { word: "freshness", translation: "tazelik", meanings: ["tazelik"] },
    { word: "gentleness", translation: "naziklik", meanings: ["naziklik","yumuşaklık"] },
    { word: "greatness", translation: "büyüklük", meanings: ["büyüklük","ululuk"] },
    { word: "keenness", translation: "isteklilik", meanings: ["isteklilik","keskinlik"] },
    { word: "laziness", translation: "tembellik", meanings: ["tembellik"] },
    { word: "loneliness", translation: "yalnızlık", meanings: ["yalnızlık"] },
    { word: "madness", translation: "delilik", meanings: ["delilik","çılgınlık"] },
    { word: "neatness", translation: "düzenlilik", meanings: ["düzenlilik","temizlik"] },
    { word: "openness", translation: "açıklık", meanings: ["açıklık","içtenlik"] },
    { word: "politeness", translation: "nezaket", meanings: ["nezaket","kibarlık"] },
    { word: "readiness", translation: "hazır olma", meanings: ["hazır olma","isteklilik"] },
    { word: "richness", translation: "zenginlik", meanings: ["zenginlik"] },
    { word: "sadness", translation: "üzüntü", meanings: ["üzüntü","hüzün"] },
    { word: "shyness", translation: "utangaçlık", meanings: ["utangaçlık","çekingenlik"] },
    { word: "smoothness", translation: "pürüzsüzlük", meanings: ["pürüzsüzlük"] },
    { word: "softness", translation: "yumuşaklık", meanings: ["yumuşaklık"] },
    { word: "steadiness", translation: "istikrar", meanings: ["istikrar","dengelilik"] },
    { word: "stillness", translation: "durgunluk", meanings: ["durgunluk","sessizlik"] },
    { word: "sweetness", translation: "tatlılık", meanings: ["tatlılık"] },
    { word: "tenderness", translation: "şefkat", meanings: ["şefkat","yumuşaklık"] },
    { word: "tiredness", translation: "yorgunluk", meanings: ["yorgunluk"] },
    { word: "vagueness", translation: "belirsizlik", meanings: ["belirsizlik","müphemlik"] },
    { word: "wilderness", translation: "vahşi doğa", meanings: ["vahşi doğa","ıssız bölge"] },
    { word: "boastful", translation: "övüngen", meanings: ["övüngen","kendini beğenmiş"] },
    { word: "doubtful", translation: "şüpheli", meanings: ["şüpheli","kararsız"] },
    { word: "eventful", translation: "olaylı", meanings: ["olaylı","hareketli"] },
    { word: "fanciful", translation: "hayali", meanings: ["hayali","düşsel"] },
    { word: "forgetful", translation: "unutkan", meanings: ["unutkan"] },
    { word: "fretful", translation: "huzursuz", meanings: ["huzursuz","huysuz"] },
    { word: "mournful", translation: "kederli", meanings: ["kederli","hüzünlü"] },
    { word: "playful", translation: "oyuncu", meanings: ["oyuncu","şakacı"] },
    { word: "remorseful", translation: "pişman", meanings: ["pişman","vicdan azabı çeken"] },
    { word: "resentful", translation: "içerlemiş", meanings: ["içerlemiş","gücenmiş"] },
    { word: "spiteful", translation: "kindar", meanings: ["kindar","garazlı"] },
    { word: "tactful", translation: "düşünceli", meanings: ["düşünceli","ince"] },
    { word: "thankful", translation: "müteşekkir", meanings: ["müteşekkir","minnettar"] },
    { word: "wishful", translation: "hülyalı", meanings: ["hülyalı","arzulu"] },
    { word: "youthful", translation: "genç", meanings: ["genç","dinç"] },
    { word: "aimless", translation: "amaçsız", meanings: ["amaçsız","gayesiz"] },
    { word: "blameless", translation: "kusursuz", meanings: ["kusursuz","suçsuz"] },
    { word: "breathless", translation: "nefes nefese", meanings: ["nefes nefese","soluk soluğa"] },
    { word: "ceaseless", translation: "durmak bilmeyen", meanings: ["durmak bilmeyen","sürekli"] },
    { word: "effortless", translation: "zahmetsiz", meanings: ["zahmetsiz","kolay"] },
    { word: "fearless", translation: "korkusuz", meanings: ["korkusuz"] },
    { word: "flawless", translation: "kusursuz", meanings: ["kusursuz","mükemmel"] },
    { word: "harmless", translation: "zararsız", meanings: ["zararsız"] },
    { word: "heedless", translation: "aldırışsız", meanings: ["aldırışsız","dikkatsiz"] },
    { word: "lawless", translation: "kanunsuz", meanings: ["kanunsuz","yasadışı"] },
    { word: "merciless", translation: "acımasız", meanings: ["acımasız","insafsız"] },
    { word: "motionless", translation: "hareketsiz", meanings: ["hareketsiz","kıpırtısız"] },
    { word: "priceless", translation: "paha biçilmez", meanings: ["paha biçilmez"] },
    { word: "reckless", translation: "pervasız", meanings: ["pervasız","umursamaz"] },
    { word: "relentless", translation: "amansız", meanings: ["amansız","acımasız"] },
    { word: "ruthless", translation: "merhametsiz", meanings: ["merhametsiz","gaddar"] },
    { word: "seamless", translation: "kesintisiz", meanings: ["kesintisiz","dikişsiz"] },
    { word: "spotless", translation: "lekesiz", meanings: ["lekesiz","tertemiz"] },
    { word: "tireless", translation: "yorulmak bilmeyen", meanings: ["yorulmak bilmeyen","yorulmaz"] },
    { word: "timeless", translation: "zamansız", meanings: ["zamansız","ölümsüz"] },
    { word: "worthless", translation: "değersiz", meanings: ["değersiz"] },
    { word: "alleviate", translation: "hafifletmek", meanings: ["hafifletmek","azaltmak"] },
    { word: "amplify", translation: "güçlendirmek", meanings: ["güçlendirmek","artırmak"] },
    { word: "annotate", translation: "açıklama eklemek", meanings: ["açıklama eklemek","not düşmek"] },
    { word: "augment", translation: "artırmak", meanings: ["artırmak","çoğaltmak"] },
    { word: "captivate", translation: "büyülemek", meanings: ["büyülemek","cezbetmek"] },
    { word: "categorize", translation: "sınıflandırmak", meanings: ["sınıflandırmak"] },
    { word: "commemorate", translation: "anmak", meanings: ["anmak","yad etmek"] },
    { word: "contradict", translation: "çelişmek", meanings: ["çelişmek","yalanlamak"] },
    { word: "counteract", translation: "etkisini gidermek", meanings: ["etkisini gidermek","karşı koymak"] },
    { word: "dramatize", translation: "dramatize etmek", meanings: ["dramatize etmek","abartmak"] },
    { word: "emanate", translation: "yayılmak", meanings: ["yayılmak","kaynaklanmak"] },
    { word: "equate", translation: "eşit saymak", meanings: ["eşit saymak","denk tutmak"] },
    { word: "exemplify", translation: "örneklemek", meanings: ["örneklemek","örnek olmak"] },
    { word: "expedite", translation: "hızlandırmak", meanings: ["hızlandırmak","çabuklaştırmak"] },
    { word: "fabricate", translation: "uydurmak", meanings: ["uydurmak","imal etmek"] },
    { word: "fluctuate", translation: "dalgalanmak", meanings: ["dalgalanmak","değişmek"] },
    { word: "generalize", translation: "genellemek", meanings: ["genellemek"] },
    { word: "hinder", translation: "engellemek", meanings: ["engellemek","ket vurmak"] },
    { word: "illuminate", translation: "aydınlatmak", meanings: ["aydınlatmak","ışıklandırmak"] },
    { word: "impede", translation: "engel olmak", meanings: ["engel olmak","sekteye uğratmak"] },
    { word: "instigate", translation: "kışkırtmak", meanings: ["kışkırtmak","tahrik etmek"] },
    { word: "intertwine", translation: "birbirine geçmek", meanings: ["birbirine geçmek","sarmalamak"] },
    { word: "liberate", translation: "özgürleştirmek", meanings: ["özgürleştirmek","kurtarmak"] },
    { word: "mediate", translation: "arabuluculuk yapmak", meanings: ["arabuluculuk yapmak"] },
    { word: "nurture", translation: "beslemek", meanings: ["beslemek","yetiştirmek"] },
    { word: "obscure", translation: "gizlemek", meanings: ["gizlemek","belirsizleştirmek"] },
    { word: "perpetuate", translation: "sürdürmek", meanings: ["sürdürmek","devam ettirmek"] },
    { word: "populate", translation: "doldurmak", meanings: ["doldurmak","yerleşmek"] },
    { word: "propagate", translation: "yaymak", meanings: ["yaymak","çoğaltmak"] },
    { word: "rectify", translation: "düzeltmek", meanings: ["düzeltmek","gidermek"] },
    { word: "redeem", translation: "telafi etmek", meanings: ["telafi etmek","kurtarmak"] },
    { word: "relinquish", translation: "vazgeçmek", meanings: ["vazgeçmek","el çekmek"] },
    { word: "renounce", translation: "feragat etmek", meanings: ["feragat etmek","reddetmek"] },
    { word: "replicate", translation: "çoğaltmak", meanings: ["çoğaltmak","kopyalamak"] },
    { word: "revitalize", translation: "canlandırmak", meanings: ["canlandırmak","yeniden hayat vermek"] },
    { word: "stipulate", translation: "şart koşmak", meanings: ["şart koşmak","belirtmek"] },
    { word: "streamline", translation: "verimli hale getirmek", meanings: ["verimli hale getirmek","sadeleştirmek"] },
    { word: "substantiate", translation: "kanıtlamak", meanings: ["kanıtlamak","doğrulamak"] },
    { word: "surpass", translation: "geçmek", meanings: ["geçmek","aşmak"] },
    { word: "synthesize", translation: "sentezlemek", meanings: ["sentezlemek","birleştirmek"] },
    { word: "transcend", translation: "aşmak", meanings: ["aşmak","üstüne çıkmak"] },
    { word: "validate", translation: "geçerli kılmak", meanings: ["geçerli kılmak","onaylamak"] },
    { word: "vindicate", translation: "haklı çıkarmak", meanings: ["haklı çıkarmak","aklamak"] },
    { word: "abstain", translation: "çekimser kalmak", meanings: ["çekimser kalmak","kaçınmak"] },
    { word: "affiliate", translation: "bağlı kuruluş", meanings: ["bağlı kuruluş","ortak olmak"] },
    { word: "aggravate", translation: "kötüleştirmek", meanings: ["kötüleştirmek","ağırlaştırmak"] },
    { word: "allude", translation: "ima etmek", meanings: ["ima etmek","değinmek"] },
    { word: "appraise", translation: "değerlendirmek", meanings: ["değerlendirmek","değer biçmek"] },
    { word: "ascertain", translation: "saptamak", meanings: ["saptamak","kesinleştirmek"] },
    { word: "assimilate", translation: "özümsemek", meanings: ["özümsemek","sindirmek"] },
    { word: "astonish", translation: "şaşırtmak", meanings: ["şaşırtmak","hayrete düşürmek"] },
    { word: "bewilder", translation: "şaşkına çevirmek", meanings: ["şaşkına çevirmek","afallatmak"] },
    { word: "compress", translation: "sıkıştırmak", meanings: ["sıkıştırmak"] },
    { word: "comprehend", translation: "kavramak", meanings: ["kavramak","anlamak"] },
    { word: "confide", translation: "sırrını açmak", meanings: ["sırrını açmak","güvenmek"] },
    { word: "culminate", translation: "doruğa ulaşmak", meanings: ["doruğa ulaşmak","sonuçlanmak"] },
    { word: "curtail", translation: "kısıtlamak", meanings: ["kısıtlamak","azaltmak"] },
    { word: "deduce", translation: "çıkarsamak", meanings: ["çıkarsamak","sonuç çıkarmak"] },
    { word: "denote", translation: "belirtmek", meanings: ["belirtmek","ifade etmek"] },
    { word: "deplete", translation: "tüketmek", meanings: ["tüketmek","azaltmak"] },
    { word: "despise", translation: "hor görmek", meanings: ["hor görmek","küçümsemek"] },
    { word: "deter", translation: "caydırmak", meanings: ["caydırmak","vazgeçirmek"] },
    { word: "discern", translation: "ayırt etmek", meanings: ["ayırt etmek","fark etmek"] },
    { word: "dispense", translation: "dağıtmak", meanings: ["dağıtmak","vermek"] },
    { word: "disperse", translation: "dağıtmak", meanings: ["dağıtmak","saçmak"] },
    { word: "dwell", translation: "ikamet etmek", meanings: ["ikamet etmek","oturmak"] },
    { word: "emit", translation: "yaymak", meanings: ["yaymak","salmak"] },
    { word: "entail", translation: "gerektirmek", meanings: ["gerektirmek","içermek"] },
  ],
  B2: [],
  C1: [],
};
